# Generated by Django 5.0.2 on 2024-02-28 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Backlog", "Backlog"),
                    ("Sprint Planning", "Sprint Planning"),
                    ("In Progress", "In Progress"),
                    ("Code Review", "Code Review"),
                    ("Testing", "Testing"),
                    ("Done", "Done"),
                ],
                default="Backlog",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Easy", "Easy"),
                    ("Medium", "Medium"),
                    ("Hard", "Hard"),
                    ("Very Hard", "Very Hard"),
                    ("Extreme", "Extreme"),
                ],
                default="Medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Critical", "Critical"),
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                ],
                default="Medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="xp_reward",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="project",
            name="xp_reward",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="task",
            name="xp_reward",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
