# Generated by Django 5.0.2 on 2024-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
