# Generated by Django 5.0.2 on 2024-02-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_note_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Review", "Review"),
                    ("Testing", "Testing"),
                    ("Done", "Done"),
                ],
                default="To Do",
                max_length=20,
            ),
        ),
    ]
