# Generated by Django 5.0.2 on 2024-03-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_userprofile_profile_picture_alter_task_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
    ]
