# Generated by Django 5.0.2 on 2024-03-01 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_task",
                to="project.userprofile",
            ),
        ),
    ]
