# Generated by Django 5.0.2 on 2024-03-02 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_alter_task_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to="project.userprofile",
            ),
        ),
    ]
