# Generated by Django 5.0.2 on 2024-03-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_alter_project_status_alter_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.ManyToManyField(related_name="projects", to="project.status"),
        ),
    ]
