# Generated by Django 5.0.2 on 2024-03-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_remove_project_status_alter_status_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="color",
            field=models.CharField(default="#00ff00", max_length=7),
        ),
    ]
