# Generated by Django 5.0.2 on 2024-03-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0015_userprofile_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_statuses",
                to="project.project",
            ),
            preserve_default=False,
        ),
    ]
