# Generated by Django 5.0.2 on 2024-03-06 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0017_remove_project_status_alter_status_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="overall_status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_status",
                to="project.status",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
