# Generated by Django 5.0.2 on 2024-03-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0018_project_overall_status_alter_status_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="grey", max_length=20)),
            ],
        ),
    ]
