# Generated by Django 5.0.2 on 2024-03-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0021_folder_task_actual_time_task_assignees_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="effort",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_template",
        ),
        migrations.RemoveField(
            model_name="task",
            name="location",
        ),
    ]
