# Generated by Django 5.0.2 on 2024-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0023_task_tags_input"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags_input",
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="project.tag"
            ),
        ),
    ]
