# Generated by Django 5.0.2 on 2024-03-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0024_remove_task_tags_input_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="overall_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="project.status",
            ),
        ),
    ]
